add takephotos coords
qbcore-framework/qb-prison pull request #7
Opened 2021-08-22 06:00 UTC by vanillla1

2021-09-14 21:32 UTC, FreakOutModz requested changes

2021-09-14 21:32 UTC, FreakOutModz commented on client/main.lua
> +RegisterNetEvent('prison:client:UnjailPerson') ---- We need someone to help write the code to return the clothes to the player after getting out of prison ---
Do not comment in PR's, do it in the github. You should remove it and request it in the comments of the PR.

2021-09-14 21:32 UTC, FreakOutModz commented on client/main.lua
> +			ClearPedProp(ped, 0)
Instead of `ClearPedProp(ped, 0)` everywhere, you should add it after the model check.

2021-09-14 21:32 UTC, FreakOutModz commented on client/main.lua
> +		end
For a cleaner code this should be:


```lua
if model == `mp_f_freemode_01` then
    ClearPedProp(ped, 0)
    SetPedComponentVariation(ped, 6, 27, 11, 2) -- Shoes
    SetPedComponentVariation(ped, 8, 14, 0, 2) -- Undershirt
    SetPedComponentVariation(ped, 5, -1, 0, 2) -- Parachute / bag
    SetPedComponentVariation(ped, 9, -1, 0, 2) -- Kevlar
    if clothesrand == 1 then
        SetPedComponentVariation(ped, 3, 3, 0, 2) -- Arms
        SetPedComponentVariation(ped, 4, 38, 0, 2) -- Leg
        SetPedComponentVariation(ped, 11, 67, 0, 2) -- Torso 2
    else
        SetPedComponentVariation(ped, 3, 14, 0, 2) -- Arms
        SetPedComponentVariation(ped, 4, 38, 1, 2) -- Leg
        SetPedComponentVariation(ped, 11, 84, 2, 2) -- Torso 2
    end
elseif model == `mp_m_freemode_01` then
    ClearPedProp(ped, 0)
    SetPedComponentVariation(ped, 3, 5, 0, 2) -- Arms
    SetPedComponentVariation(ped, 6, 6, 10, 2) -- Shoes
    SetPedComponentVariation(ped, 8, 15, 0, 2) -- Undershirt
    SetPedComponentVariation(ped, 5, -1, 0, 2) -- Parachute / bag
    SetPedComponentVariation(ped, 9, -1, 0, 2) -- Kevlar
    if clothesrand == 1 then
        SetPedComponentVariation(ped, 4, 38, 1, 2) -- Leg
        SetPedComponentVariation(ped, 11, 68, 0, 2) -- Torso 2
    else
        SetPedComponentVariation(ped, 4, 38, 0, 2) -- Leg
        SetPedComponentVariation(ped, 11, 5, 0, 2) -- Torso 2
    end
    
   ```

2021-09-14 21:32 UTC, FreakOutModz commented on client/main.lua
> +    TriggerEvent('InteractSound_CL:PlayOnOne', 'jaildoor', 1.0)
Set sound to `0.7` since `1.0` is really loud for some players.

2021-09-14 21:32 UTC, FreakOutModz commented on client/main.lua
> +    local Ped = PlayerPedId()
**NOT NECESSARY** but for a better code look this should all have the same name in script so `ped` and not `Ped`

2021-09-14 21:33 UTC, FreakOutModz commented on client/main.lua
> +			ClearPedProp(ped, 0)
I did all the code [here](https://github.com/qbcore-framework/qb-prison/pull/7#discussion_r708647219)

2021-09-15 12:54 UTC, FreakOutModz approved these changes
Nice work

2021-09-21 09:18 UTC, evanillaa commented
Please do not close the proposal
I hope you can fix the errors, if any
And come out with a good text
I'm not a good expert at finishing code well
But I try to help a lot
I hope everyone will participate in solving the problems
I thank you @GhzGarage @FreakOutModz thank for all support this project

2021-09-21 21:12 UTC, FreakOutModz approved these changes
Changes looking good.

2021-09-21 21:24 UTC, evanillaa commented
Hey, FreakOutModz
Long time no see your response

2021-10-31 21:05 UTC, closed without merging